# Generated by Django 3.2.5 on 2021-07-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='user',
        ),
    ]
